### ISSUE TITLE
3d mshmet missing

### ISSUE THREAD

**Issue by loicNorgeot** [ICStoolbox/AdaptTools#2]
See src/mshmet_3d: main = return(1)

**Comment by f-p-b** [comment]
Wondering about this still empty (missing) file and were I can procure a working version. Any help is welcome

**Comment by Algiane** [comment]
Hello,

You can use the branch [olderVersionThatWorks](https://github.com/ISCDtoolbox/AdaptTools/tree/olderVersionThatWorks) in which you will find an old version of mshmet with the 3D implementation. 
Just take care that the shortcuts for the command line arguments may differ between both versions.

Regards,
Algiane
