### ISSUE TITLE
cmake problem?

### ISSUE THREAD

**Issue by edljk** [ICStoolbox/AdaptTools#3]
Trying to compile under linux ubuntu 18.04 I obtain after mkdir build:

```

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Commons
    linked by target "MshInt_a" in directory /home/oudet/C/Mmg/AdaptTools
    linked by target "MshMet_a" in directory /home/oudet/C/Mmg/AdaptTools

-- Configuring incomplete, errors occurred!
```

any help welcome

**Comment by Algiane** [comment]
Hi,

you need to install the Commons library of the ISCDToolbox project ([https://github.com/ISCDtoolbox/Commons](https://github.com/ISCDtoolbox/Commons)).
(I will update the CMakeLists.txt file to make the message associated to the Commons variable more clear, at least with ccmake).

Best

**Comment by edljk** [comment]
Perfect, thanks!
